### ISSUE TITLE
How to make a group and send message ?

### ISSUE THREAD

**Issue by zNiGhTFuRyZNTT** [uriyyo/instapi#113]

**Comment by uriyyo** [comment]
Hi @zNiGhTFuRyZNTT,

It is not implemented. We are planning to add this feature to the upcoming release.

**Comment by zNiGhTFuRyZNTT** [comment]
Yes that would be so great, I was so curious about what I saw in direct.py Class Direct.
I thought this code could create a group with a number of usernames but it didn't work
```
    @classmethod
    def create(cls: Type[ModelT_co], data: Any) -> ModelT_co:
        return super().create(  # type: ignore
            {
                **data,
                "users": tuple(map(User.create, data["users"])),
            }
        )
```

**Comment by uriyyo** [comment]
> Yes that would be so great, I was so curious about what I saw in direct.py Class Direct.

This method is used to create an entity from a raw JSON data
