### ISSUE TITLE
Need implementation of getting post messages

### ISSUE THREAD

**Issue by vol1ura** [uriyyo/instapi#82]
There is not enough method to extract the text of posts using the public API.
Currently it is needed to use low-level API method `_media_info` to get a post caption.

*Example*
```python
user = User.from_username('9gag')

f, = user.feeds(limit=1)
print(f._media_info()['caption']['text'])
```

**Comment by uriyyo** [comment]
Thanks, for submitting an issue, we will implement it as soon as possible
